# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |vb| 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.box = "precise64"
	config.vm.provision :shell, :path => "provisioning/bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8081
  config.vm.network :forwarded_port, guest: 443, host: 8091
  
  config.vm.synced_folder "wp-content/uploads", "/vagrant/wp-content/uploads", id: "uploads", :mount_options => ["dmode=777,fmode=777"]
  config.vm.synced_folder "wp-content/uploads/wp-migrate-db", "/vagrant/wp-content/uploads/wp-migrate-db", id: "migrate-db-uploads", :mount_options => ["dmode=777,fmode=777"]
end
